### ISSUE TITLE
HTTPRequest in bulk data was malformed.

### ISSUE THREAD

**Issue by justinjdickow** [smartdevicelink/sdl_core#127]
While trying to do a policy table update by sending the Proprietary system request from SDL Core to SDL Server I get the below error logged out from Sync Proxy Tester.

```java
E/OnSystemRequest(  377): HTTPRequest in bulk data was malformed.
W/System.err(  377): org.json.JSONException: Value 4Ezay^ק<yi'*' of type java.lang.String cannot be converted to JSONObject
W/System.err(  377): 	at org.json.JSON.typeMismatch(JSON.java:111)
W/System.err(  377): 	at org.json.JSONObject.<init>(JSONObject.java:160)
W/System.err(  377): 	at org.json.JSONObject.<init>(JSONObject.java:173)
W/System.err(  377): 	at com.smartdevicelink.proxy.rpc.OnSystemRequest.handleBulkData(OnSystemRequest.java:57)
W/System.err(  377): 	at com.smartdevicelink.proxy.rpc.OnSystemRequest.setBulkData(OnSystemRequest.java:114)
W/System.err(  377): 	at com.smartdevicelink.proxy.rpc.OnSystemRequest.<init>(OnSystemRequest.java:44)
W/System.err(  377): 	at com.smartdevicelink.proxy.rpc.OnSystemRequest.<init>(OnSystemRequest.java:39)
W/System.err(  377): 	at com.smartdevicelink.proxy.SdlProxyBase.handleRPCMessage(SdlProxyBase.java:2707)
W/System.err(  377): 	at com.smartdevicelink.proxy.SdlProxyBase.dispatchIncomingMessage(SdlProxyBase.java:1391)
W/System.err(  377): 	at com.smartdevicelink.proxy.SdlProxyBase.access$2100(SdlProxyBase.java:100)
W/System.err(  377): 	at com.smartdevicelink.proxy.SdlProxyBase$2.dispatch(SdlProxyBase.java:571)
W/System.err(  377): 	at com.smartdevicelink.proxy.SdlProxyBase$2.dispatch(SdlProxyBase.java:568)
W/System.err(  377): 	at com.smartdevicelink.Dispatcher.ProxyMessageDispatcher.handleMessages(ProxyMessageDispatcher.java:45)
W/System.err(  377): 	at com.smartdevicelink.Dispatcher.ProxyMessageDispatcher.access$000(ProxyMessageDispatcher.java:8)
W/System.err(  377): 	at com.smartdevicelink.Dispatcher.ProxyMessageDispatcher$1.run(ProxyMessageDispatcher.java:23)
W/System.err(  377): 	at java.lang.Thread.run(Thread.java:818)
```

When I open the request on Android, the 0x07 endpoint does not appear in the JSON.

**Comment by justinjdickow** [comment]
SDL retrieves the headers from the file [PROPRIETARY_REQUEST](https://github.com/smartdevicelink/sdl_core/blob/master/src/components/HMI/IVSU/PROPRIETARY_REQUEST). The contents appear to be encrypted and were not being handled by the proxy we were using. Putting a JSON object with valid http headers in this files fixes this particular issue.
