### ISSUE TITLE
sdl with qt5 hmi and dbus adapter not work on ubuntu 12.04 X86_64

### ISSUE THREAD

**Issue by chenbd** [smartdevicelink/sdl_core#29]
sdl with qt5 hmi and dbus adapter not work on ubuntu 12.04 X86_64, but seems to work on ubuntu 12.04 i686.  sdl with web hmi work on ubuntu 12.04 x86_64.
# seems dbus releated problem

```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff7fdf700 (LWP 8378)]
0x00007ffff64ae9f9 in ?? () from /lib/x86_64-linux-gnu/libdbus-1.so.3
(gdb) bt
#0  0x00007ffff64ae9f9 in ?? () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#1  0x00007ffff64aef66 in ?? () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#2  0x00007ffff64b347c in dbus_message_iter_open_container () from /lib/x86_64-linux-gnu/libdbus-1.so.3
#3  0x00000000015a4084 in dbus::DBusAdapter::SetStructValue (this=0x1df4a80, iter=0x7ffff7fdd860, rules=0x1cacf00, structure=...)
    at /home/chenbd/github/sdl_core/src/components/dbus/src/dbus_adapter.cc:625
#4  0x00000000015a2ba0 in dbus::DBusAdapter::SetValue (this=0x1df4a80, iter=0x7ffff7fdd860, rules=0x1cacf00, param=...)
    at /home/chenbd/github/sdl_core/src/components/dbus/src/dbus_adapter.cc:521
#5  0x00000000015a3ade in dbus::DBusAdapter::SetArrayValue (this=0x1df4a80, iter=0x7ffff7fddec0, rules=0x1cacf20, param=...)
    at /home/chenbd/github/sdl_core/src/components/dbus/src/dbus_adapter.cc:602
#6  0x00000000015a2b74 in dbus::DBusAdapter::SetValue (this=0x1df4a80, iter=0x7ffff7fddec0, rules=0x1cacf20, param=...)
    at /home/chenbd/github/sdl_core/src/components/dbus/src/dbus_adapter.cc:515
#7  0x00000000015a2831 in dbus::DBusAdapter::SetOneArgument (this=0x1df4a80, iter=0x7ffff7fddec0, rules=0x1cacf20, param=...)
    at /home/chenbd/github/sdl_core/src/components/dbus/src/dbus_adapter.cc:488
#8  0x00000000015a2782 in dbus::DBusAdapter::SetArguments (this=0x1df4a80, msg=0x1e0b880, rules=..., args=...)
    at /home/chenbd/github/sdl_core/src/components/dbus/src/dbus_adapter.cc:476
#9  0x000000000159d997 in dbus::DBusAdapter::MethodCall (this=0x1df4a80, id=1, 
    func_id=hmi_apis::FunctionID::BasicCommunication_UpdateDeviceList, name=..., obj=...)
    at /home/chenbd/github/sdl_core/src/components/dbus/src/dbus_adapter.cc:242
#10 0x0000000001426784 in hmi_message_handler::DBusMessageAdapter::Request (this=0x1df4a70, obj=...)
    at /home/chenbd/github/sdl_core/src/components/hmi_message_handler/src/dbus_message_adapter.cc:179
#11 0x000000000142125a in hmi_message_handler::DBusMessageAdapter::SendMessageToHMI (this=0x1df4a70, message=...)
    at /home/chenbd/github/sdl_core/src/components/hmi_message_handler/src/dbus_message_adapter.cc:76
#12 0x00000000014157d7 in hmi_message_handler::HMIMessageHandlerImpl::Handle (this=0x1d74dd0, message=...)
    at /home/chenbd/github/sdl_core/src/components/hmi_message_handler/src/hmi_message_handler_impl.cc:121
#13 0x000000000141f2e4 in threads::MessageLoopThread<utils::PrioritizedQueue<hmi_message_handler::impl::MessageToHmi> >::LoopThreadDelegate::DrainQue (this=0x1dad700) at /home/chenbd/github/sdl_core/src/components/include/utils/threads/message_loop_thread.h:167
#14 0x000000000141f016 in threads::MessageLoopThread<utils::PrioritizedQueue<hmi_message_handler::impl::MessageToHmi> >::LoopThreadDelegate::threadMain (this=0x1dad700) at /home/chenbd/github/sdl_core/src/components/include/utils/threads/message_loop_thread.h:147
#15 0x00007ffff7bbbcbe in threads::(anonymous namespace)::threadFunc (arg=0x1dad750)
    at /home/chenbd/github/sdl_core/src/components/utils/src/threads/posix_thread.cc:64
#16 0x00007ffff7989e9a in start_thread (arg=0x7ffff7fdf700) at pthread_create.c:308
#17 0x00007ffff55a82ed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:112
#18 0x0000000000000000 in ?? ()
```

**Comment by JackLivio** [comment]
Ubuntu 12 is not supported. There have been some changes made to the dbus library and the QT HMI in core so this issue is outdated.
